name: HowSAuth
version: '${version}'
main: org.howsauth.plugin.HowSAuth
api-version: '1.21'
load: STARTUP
authors:
  - HowSberban
description: A login plugin with Paper API.
license: GPL-3.0
folia-supported: true
loader: org.howsauth.plugin.PluginLoaderImpl

dependencies:
  server:
    packetevents:
      load: BEFORE
      required: true
    PlaceholderAPI:
      load: BEFORE
      required: false

permissions:
  hsauth.admin:
    description: 管理员权限
    default: op
